experiment_name: 03_cnn_fashion_mnist

seed: 42

data:
  root: data/raw
  batch_size: 64

training:
  epochs: 10
  learning_rate: 0.001
  checkpoint_dir: checkpoints/03_cnn_fashion_mnist
  checkpoint_every: 1
  show_progress: true
  model_path: model/cnn_fashion_mnist.pt

visualization:
  figures_dir: reports/figures
  show_fig: false

logging:
  disable_logging: false
  log_level: INFO
  log_path: logs/03_cnn_fashion_mnist/train.log
